server {
    listen 8080;
    listen [::]:8080;
    server_name localhost;

    include /etc/nginx/conf.d/redirects.conf;

    root /usr/share/nginx/html;

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
